# Generated by Django 5.0.2 on 2026-05-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0003_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='GradoAcademico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='categoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
