# Generated by Django 5.0.2 on 2026-05-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0004_administradores_gradoacademico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestros',
            name='campus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
