# Generated by Django 5.0.2 on 2026-05-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0005_maestros_campus_maestros_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='sexo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
