# Generated by Django 5.0.2 on 2026-05-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0006_alumnos_direccion_alumnos_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
